framework:
    secret: '%env(APP_SECRET)%'
    session: true
    serializer:
        enabled: true
    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    trusted_hosts: '%env(TRUSTED_HOSTS)%'
    exceptions:
        Symfony\Component\HttpKernel\Exception\NotFoundHttpException:
            log_level: info
        Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException:
            log_level: info

when@prod:
    framework:
        session: false

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
