framework:
    messenger:
        buses:
            command.bus:
                middleware:
                    - 'App\Shared\Infrastructure\Telemetry\TraceBoundedContextMiddleware'
                    - doctrine_transaction: ['organization']

        transports:
            to_organization:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%?queue_name=to_organization'
                serializer: 'App\Organization\Organization\Infrastructure\Bus\OrganizationMessageSerializer'
